name = input("What is your name? ")
course = input("What course are you studying? ")
favourite = input("What are of cybersecurity interests you? ")
print("Hello, " + name + "!")
print("You are studying " + course)
print("You are interested in " + favourite)