name = input("What is your name? ")
student_id = input("What is your student number? ")
year = input("What year are you currently in? ")
print("Name: " +name)
print("Student Number " +student_id)
print("Year: " +year)
